[package]
name = "rxhkd"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.75"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
strum = { version = "0.25.0", features = ["derive"] }
xcb = { version = "1.2.2" }
